TEST_DEPS="(snow bytevector)" \
          "(seth message-digest primitive)" \
          "(seth message-digest type)" \
          "(seth message-digest bv)" \
          "(seth message-digest port)"
include ../../../makefiles/test.make

clean-extra:
