(define (main-program)
  (display (make-random-u8vector 10))
  (newline)
  (display (make-random-u8vector 10))
  (newline)
  (display (random-fixnum 1000))
  (newline)
  (display (random-bignum 1000))
  (newline)

  #t)
