(repository
  (sibling
    (name "Snow Repository")
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/")
    (trust 1.0))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/assert.tgz")
    (size 3095)
    (checksum (md5 "f9fc9da6c69d2dbbd4b0ef72b5e95ffd"))
    (library
      (name (snow assert))
      (path "snow/assert.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "assert")
      (license lgpl/v2.1)
      (depends (snow snowlib))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/bignum.tgz")
    (size 39447)
    (checksum (md5 "2b01de11be03e9178f4c60b5d4fc6edb"))
    (library
      (name (snow bignum))
      (path "snow/bignum.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Operations on large integers." math snow)
      (license lgpl/v2.1)
      (depends (snow bytevector))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/binio.tgz")
    (size 9751)
    (checksum (md5 "eccf0309b21e1d1aaa143e27bc399355"))
    (library
      (name (snow binio))
      (path "snow/binio.sld")
      (version "1.0.2")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Binary I/O." i/o snow)
      (license lgpl/v2.1)
      (depends (snow snowlib) (snow bytevector))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/bytevector.tgz")
    (size 13847)
    (checksum (md5 "6bec7305a8e25e32317c2b7ea9e5eac0"))
    (library
      (name (snow bytevector))
      (path "snow/bytevector.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "bytevector compatibility layer")
      (license bsd)
      (depends (snow gauche-bv-string-utils)))
    (library
      (name (snow gauche-bv-string-utils))
      (path "snow/gauche-bv-string-utils.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "bytevector compatibility layer")
      (license bsd)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/digest.tgz")
    (size 64023)
    (checksum (md5 "9aad8b62e4a6a027fb9c11f775cf611f"))
    (library
      (name (snow digest))
      (path "snow/digest.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description
        "Computation of message digests (CRC32, MD5, SHA-1, ...)."
        hash
        conv
        snow)
      (license lgpl/v2.1)
      (depends
        (snow srfi-60-integers-as-bits)
        (snow binio)
        (snow bytevector)
        (snow binio))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/extio.tgz")
    (size 39447)
    (checksum (md5 "d8d3fdedc751699a09cb6b4175ce9d00"))
    (library
      (name (snow extio))
      (path "snow/extio.sld")
      (version "1.0.3")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Seth Alves <alves@hungry.com>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Extended I/O." i/o snow)
      (license lgpl/v2.1)
      (depends
        (snow snowlib)
        (snow binio)
        (snow bytevector)
        (snow srfi-60-integers-as-bits)
        (snow gauche-extio-utils)))
    (library
      (name (snow gauche-extio-utils))
      (path "snow/gauche-extio-utils.sld")
      (version "1.0.3")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Seth Alves <alves@hungry.com>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Extended I/O." i/o snow)
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/filesys.tgz")
    (size 34327)
    (checksum (md5 "c60eab123b0759044ead6bfc4789ebf8"))
    (library
      (name (snow filesys))
      (path "snow/filesys.sld")
      (version "1.0.4")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "File system access." os snow)
      (license lgpl/v2.1)
      (depends
        (snow random)
        (snow srfi-13-strings)
        (snow bytevector)
        (snow gauche-filesys-utils)))
    (library
      (name (snow gauche-filesys-utils))
      (path "snow/gauche-filesys-utils.sld")
      (version "1.0.4")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "File system access." os snow)
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/genport.tgz")
    (size 13847)
    (checksum (md5 "1f4c1010104543fa16dbc73783bfdf4e"))
    (library
      (name (snow genport))
      (path "snow/genport.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Generic ports." i/o snow)
      (license lgpl/v2.1)
      (depends (snow binio) (snow bytevector) (snow gauche-genport-utils)))
    (library
      (name (snow gauche-genport-utils))
      (path "snow/gauche-genport-utils.sld")
      (version "1.0")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "Generic ports." i/o snow)
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/hello.tgz")
    (size 3095)
    (checksum (md5 "ca1dc3d8fd6387ae3971fa63dfada579"))
    (library
      (name (snow hello))
      (path "snow/hello.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Display \"let it snow\" and pi." example snow)
      (license lgpl/v2.1)
      (depends (snow pi))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/input-parse.tgz")
    (size 12311)
    (checksum (md5 "8f6374ebb031b5ddb2090faa9acf8419"))
    (library
      (name (snow input-parse))
      (path "snow/input-parse.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description
        "inspired and compatible with Oleg Kiselyov's input parsing library")
      (license public-domain)
      (depends (snow snowlib) (snow srfi-13-strings))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/pi.tgz")
    (size 4631)
    (checksum (md5 "424f61286dda2d827d4b0496639ea189"))
    (library
      (name (snow pi))
      (path "snow/pi.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Computes the digits of pi." example snow)
      (license lgpl/v2.1)
      (depends (snow bignum))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/processio.tgz")
    (size 8727)
    (checksum (md5 "2e3f477bb66f0e1533128aebda4227e7"))
    (library
      (name (snow processio))
      (path "snow/processio.sld")
      (version "1.0.0")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Seth Alves <alves@hungry.com")
      (authors
        "Nils M Holm <nmh at t3x.org>"
        "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "I/O to operating system subprocesses." i/o os)
      (license bsdl)
      (depends (snow snowlib) (snow extio) (snow filesys))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/random.tgz")
    (size 5143)
    (checksum (md5 "ca645604cd8d5452449bfa265d4a4a11"))
    (library
      (name (snow random))
      (path "snow/random.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "High-quality random number generation." snow)
      (license lgpl/v2.1)
      (depends (snow binio) (snow bytevector) (snow bignum))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/snowlib.tgz")
    (size 24087)
    (checksum (md5 "b73822cf5622e4ac0bdf5f5e951a4df9"))
    (library
      (name (snow snowlib))
      (path "snow/snowlib.sld")
      (version "1.2.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Scheme Now! runtime library." snow)
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-13-strings.tgz")
    (size 15895)
    (checksum (md5 "5e290b061c70d5217bb21abe1d1d45d8"))
    (library
      (name (snow srfi-13-strings))
      (path "snow/srfi-13-strings.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors)
      (description "srfi-13-strings")
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-19-time.tgz")
    (size 58903)
    (checksum (md5 "eb45b5781d70e1b62f3c2d17733fcdb9"))
    (library
      (name (snow srfi-19-time))
      (path "snow/srfi-19-time.sld")
      (version "1.0")
      (homepage "http://srfi.schemers.org/srfi-19/srfi-19.html")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Will Fitzgerald" "Neodesic Corporation")
      (description "srfi-19-time")
      (license BSD-style)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-29-format.tgz")
    (size 10775)
    (checksum (md5 "13aee06dbe469342cec108b04e630b0e"))
    (library
      (name (snow srfi-29-format))
      (path "snow/srfi-29-format.sld")
      (version "1.0")
      (homepage "http://srfi.schemers.org/srfi-29/srfi-29.html")
      (maintainers)
      (authors)
      (description "srfi-29-format")
      (license mit)
      (depends (snow snowlib))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-60-integers-as-bits.tgz")
    (size 9751)
    (checksum (md5 "4ae3383fe946486e6685e44ac4d8d356"))
    (library
      (name (snow srfi-60-integers-as-bits))
      (path "snow/srfi-60-integers-as-bits.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "bytevector compatibility layer")
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-95-sort.tgz")
    (size 12823)
    (checksum (md5 "cd675f797e51850b448ba2a7918ec384"))
    (library
      (name (snow srfi-95-sort))
      (path "snow/srfi-95-sort.sld")
      (version "1.0")
      (homepage
        "http://srfi.schemers.org/srfi-95/srfi-95.html"
        "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Aubrey Jaffer" "Richard A. O'Keefe" "D.H.D. Warren")
      (description "Sorting and Merging")
      (license public-domain)
      (depends (snow bytevector) (snow gauche-sort-utils)))
    (library
      (name (snow gauche-sort-utils))
      (path "snow/gauche-sort-utils.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "Sorting and Merging")
      (license public-domain)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/tar.tgz")
    (size 25111)
    (checksum (md5 "55d0a087f38a6a86396be1ec728b1d1c"))
    (library
      (name (snow tar))
      (path "snow/tar.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "TAR file format packing and unpacking." conv snow)
      (license lgpl/v2.1)
      (depends
        (snow snowlib)
        (snow bytevector)
        (snow srfi-60-integers-as-bits)
        (snow bignum)
        (snow genport)
        (snow filesys))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/zlib.tgz")
    (size 45591)
    (checksum (md5 "4db34b925317461c15bbec06800f0bfd"))
    (library
      (name (snow zlib))
      (path "snow/zlib.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors
        "Marc Feeley <feeley at iro.umontreal.ca>"
        "Manuel Serrano <Manuel.Serrano at sophia.inria.fr>")
      (description
        "Compression and decompression of deflate and gzip formats."
        conv
        i/o
        snow)
      (license lgpl/v2.1)
      (depends
        (snow snowlib)
        (snow bytevector)
        (snow digest)
        (snow srfi-60-integers-as-bits)
        (snow genport)
        (snow digest)))))
