(repository
  (sibling
    (name "Snow Repository")
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/")
    (trust 1.0))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-14-character-sets.tgz")
    (size 39959)
    (checksum (md5 "4b36916ecc3f59f5a9f584f6bf9e08e9"))
    (library
      (name (snow srfi-14-character-sets))
      (path "snow/srfi-14-character-sets.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "srfi-14-character-sets")
      (license BSD-style)
      (depends (snow srfi-60-integers-as-bits))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-1-lists.tgz")
    (size 27159)
    (checksum (md5 "1a3923e5d43e38089f8b6adc1ed99060"))
    (library
      (name (snow srfi-1-lists))
      (path "snow/srfi-1-lists.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors)
      (description "srfi-1-lists")
      (license olin-shivers-doesnt-care)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/assert.tgz")
    (size 2583)
    (checksum (md5 "3793b7d97c4ae74dd175f451ffd5aa43"))
    (library
      (name (snow assert))
      (path "snow/assert.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "assert")
      (license bsd)
      (depends (snow snowlib))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/bignum.tgz")
    (size 39447)
    (checksum (md5 "63c3fc670e69cfd993f37879b06c4680"))
    (library
      (name (snow bignum))
      (path "snow/bignum.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Operations on large integers." math snow)
      (license lgpl/v2.1)
      (depends (snow bytevector))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/binio.tgz")
    (size 8215)
    (checksum (md5 "0c4c678fa58dbc38c013232ebb9b835e"))
    (library
      (name (snow binio))
      (path "snow/binio.sld")
      (version "1.0.2")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Binary I/O." i/o snow)
      (license lgpl/v2.1)
      (depends (snow bytevector))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/bytevector.tgz")
    (size 13847)
    (checksum (md5 "590e5776a6d3ac19fd4f68902b6628b3"))
    (library
      (name (snow bytevector))
      (path "snow/bytevector.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "bytevector compatibility layer")
      (license bsd)
      (depends (snow srfi-1-lists) (snow gauche-bv-string-utils)))
    (library
      (name (snow gauche-bv-string-utils))
      (path "snow/gauche-bv-string-utils.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "bytevector compatibility layer")
      (license bsd)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/digest.tgz")
    (size 64023)
    (checksum (md5 "80bf844f2778862a64ab4b5cbf6eb611"))
    (library
      (name (snow digest))
      (path "snow/digest.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description
        "Computation of message digests (CRC32, MD5, SHA-1, ...)."
        hash
        conv
        snow)
      (license lgpl/v2.1)
      (depends
        (snow srfi-60-integers-as-bits)
        (snow binio)
        (snow bytevector))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/extio.tgz")
    (size 40983)
    (checksum (md5 "99955b7cfca2e86992028e04be647ef7"))
    (library
      (name (snow extio))
      (path "snow/extio.sld")
      (version "1.0.3")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Seth Alves <alves@hungry.com>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Extended I/O." i/o snow)
      (license lgpl/v2.1)
      (depends
        (snow gauche-extio-utils)
        (snow snowlib)
        (snow bytevector)
        (snow srfi-60-integers-as-bits)
        (snow srfi-13-strings)))
    (library
      (name (snow gauche-extio-utils))
      (path "snow/gauche-extio-utils.sld")
      (version "1.0.3")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Seth Alves <alves@hungry.com>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Extended I/O." i/o snow)
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/filesys.tgz")
    (size 34327)
    (checksum (md5 "4550500eadd138f0d6d0cc691ea0008e"))
    (library
      (name (snow filesys))
      (path "snow/filesys.sld")
      (version "1.0.4")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "File system access." os snow)
      (license lgpl/v2.1)
      (depends (snow srfi-13-strings) (snow gauche-filesys-utils)))
    (library
      (name (snow gauche-filesys-utils))
      (path "snow/gauche-filesys-utils.sld")
      (version "1.0.4")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "File system access." os snow)
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/genport.tgz")
    (size 13847)
    (checksum (md5 "d017bce553b6bcbd07435218de60ed56"))
    (library
      (name (snow genport))
      (path "snow/genport.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Generic ports." i/o snow)
      (license lgpl/v2.1)
      (depends (snow bytevector) (snow binio) (snow gauche-genport-utils)))
    (library
      (name (snow gauche-genport-utils))
      (path "snow/gauche-genport-utils.sld")
      (version "1.0")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "Generic ports." i/o snow)
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/hello.tgz")
    (size 3095)
    (checksum (md5 "238dd25279324114307401f5b5176b83"))
    (library
      (name (snow hello))
      (path "snow/hello.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Display \"let it snow\" and pi." example snow)
      (license lgpl/v2.1)
      (depends (snow pi))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/input-parse.tgz")
    (size 12311)
    (checksum (md5 "342acccfbe28524c9102368341bfa348"))
    (library
      (name (snow input-parse))
      (path "snow/input-parse.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description
        "inspired and compatible with Oleg Kiselyov's input parsing library")
      (license public-domain)
      (depends (snow snowlib) (snow srfi-13-strings))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/pi.tgz")
    (size 4631)
    (checksum (md5 "e3e73583c1b34382b19d39c24af4a9a0"))
    (library
      (name (snow pi))
      (path "snow/pi.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Computes the digits of pi." example snow)
      (license lgpl/v2.1)
      (depends (snow bignum))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/processio.tgz")
    (size 8727)
    (checksum (md5 "85dc19aae24091eca9580eb8b9df8890"))
    (library
      (name (snow processio))
      (path "snow/processio.sld")
      (version "1.0.0")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Seth Alves <alves@hungry.com")
      (authors
        "Nils M Holm <nmh at t3x.org>"
        "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "I/O to operating system subprocesses." i/o os)
      (license bsdl)
      (depends (snow snowlib) (snow filesys) (snow extio))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/random.tgz")
    (size 5143)
    (checksum (md5 "5c5ad034464c4b20d429a20ac70b4df7"))
    (library
      (name (snow random))
      (path "snow/random.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "High-quality random number generation." snow)
      (license lgpl/v2.1)
      (depends (snow bytevector) (snow binio) (snow bignum))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/snowlib.tgz")
    (size 14359)
    (checksum (md5 "1ab54c941a85069932f09cfaae385c32"))
    (library
      (name (snow snowlib))
      (path "snow/snowlib.sld")
      (version "1.2.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Scheme Now! runtime library." snow)
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-13-strings.tgz")
    (size 16407)
    (checksum (md5 "77709a23aba01d611091832011d3e38d"))
    (library
      (name (snow srfi-13-strings))
      (path "snow/srfi-13-strings.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors)
      (description "srfi-13-strings")
      (license lgpl/v2.1)
      (depends (snow srfi-14-character-sets))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-19-time.tgz")
    (size 58903)
    (checksum (md5 "4e1fe57377f7465456d44d0302b14c86"))
    (library
      (name (snow srfi-19-time))
      (path "snow/srfi-19-time.sld")
      (version "1.0")
      (homepage "http://srfi.schemers.org/srfi-19/srfi-19.html")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Will Fitzgerald" "Neodesic Corporation")
      (description "srfi-19-time")
      (license BSD-style)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-29-format.tgz")
    (size 10775)
    (checksum (md5 "12c44f174179023f8c72d3e4223865bb"))
    (library
      (name (snow srfi-29-format))
      (path "snow/srfi-29-format.sld")
      (version "1.0")
      (homepage "http://srfi.schemers.org/srfi-29/srfi-29.html")
      (maintainers)
      (authors)
      (description "srfi-29-format")
      (license mit)
      (depends (snow snowlib))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-60-integers-as-bits.tgz")
    (size 9751)
    (checksum (md5 "3c0b385da0bcd0f047999deee530e384"))
    (library
      (name (snow srfi-60-integers-as-bits))
      (path "snow/srfi-60-integers-as-bits.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "bytevector compatibility layer")
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-95-sort.tgz")
    (size 12823)
    (checksum (md5 "dc667c37732267f4e56c580f8921619f"))
    (library
      (name (snow srfi-95-sort))
      (path "snow/srfi-95-sort.sld")
      (version "1.0")
      (homepage
        "http://srfi.schemers.org/srfi-95/srfi-95.html"
        "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Aubrey Jaffer" "Richard A. O'Keefe" "D.H.D. Warren")
      (description "Sorting and Merging")
      (license public-domain)
      (depends (snow gauche-sort-utils) (snow bytevector)))
    (library
      (name (snow gauche-sort-utils))
      (path "snow/gauche-sort-utils.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "Sorting and Merging")
      (license public-domain)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/tar.tgz")
    (size 25111)
    (checksum (md5 "58c87675cfc18fcd6f5ff1f4aa098aa6"))
    (library
      (name (snow tar))
      (path "snow/tar.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "TAR file format packing and unpacking." conv snow)
      (license lgpl/v2.1)
      (depends
        (snow snowlib)
        (snow bytevector)
        (snow srfi-60-integers-as-bits)
        (snow bignum)
        (snow genport)
        (snow filesys))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/zlib.tgz")
    (size 45591)
    (checksum (md5 "c3c67168a985d3ef8820f3ff13744199"))
    (library
      (name (snow zlib))
      (path "snow/zlib.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors
        "Marc Feeley <feeley at iro.umontreal.ca>"
        "Manuel Serrano <Manuel.Serrano at sophia.inria.fr>")
      (description
        "Compression and decompression of deflate and gzip formats."
        conv
        i/o
        snow)
      (license lgpl/v2.1)
      (depends
        (snow snowlib)
        (snow bytevector)
        (snow digest)
        (snow srfi-60-integers-as-bits)
        (snow genport)))))
