(repository
  (sibling
    (name "Snow Repository")
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/")
    (trust 1.0))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-14-character-sets.tgz")
    (size 39959)
    (checksum (md5 "5140f7ffe4d1d3d47e21d622d3913620"))
    (library
      (name ())
      (path "snow/srfi-14-character-sets.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "srfi-14-character-sets")
      (license BSD-style)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-1-lists.tgz")
    (size 27159)
    (checksum (md5 "c17fab8efeab75e34d72d13528b8d3ce"))
    (library
      (name (snow srfi-1-lists))
      (path "snow/srfi-1-lists.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors)
      (description "srfi-1-lists")
      (license olin-shivers-doesnt-care)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/assert.tgz")
    (size 2583)
    (checksum (md5 "701c9fea89b8dcd6dde68867b07418e0"))
    (library
      (name (snow assert))
      (path "snow/assert.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "assert")
      (license bsd)
      (depends (snow snowlib))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/bignum.tgz")
    (size 39447)
    (checksum (md5 "8a8f11348c6ca13fd7463b2ca080c09d"))
    (library
      (name (snow bignum))
      (path "snow/bignum.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Operations on large integers." math snow)
      (license lgpl/v2.1)
      (depends (snow bytevector))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/binio.tgz")
    (size 8215)
    (checksum (md5 "567de74cf6ceef1ad7526224bdd6afba"))
    (library
      (name (snow binio))
      (path "snow/binio.sld")
      (version "1.0.2")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Binary I/O." i/o snow)
      (license lgpl/v2.1)
      (depends (snow bytevector))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/bytevector.tgz")
    (size 13847)
    (checksum (md5 "9ab714feb693183b7cb2a422fae79f5e"))
    (library
      (name (snow bytevector))
      (path "snow/bytevector.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "bytevector compatibility layer")
      (license bsd)
      (depends (snow srfi-1-lists) (snow gauche-bv-string-utils)))
    (library
      (name (snow gauche-bv-string-utils))
      (path "snow/gauche-bv-string-utils.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "bytevector compatibility layer")
      (license bsd)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/digest.tgz")
    (size 64023)
    (checksum (md5 "8f5cfb52a23dc77bc14976d7546bc4a9"))
    (library
      (name (snow digest))
      (path "snow/digest.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description
        "Computation of message digests (CRC32, MD5, SHA-1, ...)."
        hash
        conv
        snow)
      (license lgpl/v2.1)
      (depends
        (snow srfi-60-integers-as-bits)
        (snow binio)
        (snow bytevector))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/extio.tgz")
    (size 40983)
    (checksum (md5 "6f29ac52c97b6fbab7ee534951666b52"))
    (library
      (name (snow extio))
      (path "snow/extio.sld")
      (version "1.0.3")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Seth Alves <alves@hungry.com>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Extended I/O." i/o snow)
      (license lgpl/v2.1)
      (depends
        (snow gauche-extio-utils)
        (snow snowlib)
        (snow bytevector)
        (snow srfi-60-integers-as-bits)
        (snow srfi-13-strings)))
    (library
      (name (snow gauche-extio-utils))
      (path "snow/gauche-extio-utils.sld")
      (version "1.0.3")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Seth Alves <alves@hungry.com>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Extended I/O." i/o snow)
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/filesys.tgz")
    (size 34327)
    (checksum (md5 "8bb0ec10968812b485a8f9931640a5ad"))
    (library
      (name (snow filesys))
      (path "snow/filesys.sld")
      (version "1.0.4")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "File system access." os snow)
      (license lgpl/v2.1)
      (depends (snow srfi-13-strings) (snow gauche-filesys-utils)))
    (library
      (name (snow gauche-filesys-utils))
      (path "snow/gauche-filesys-utils.sld")
      (version "1.0.4")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "File system access." os snow)
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/genport.tgz")
    (size 13847)
    (checksum (md5 "96e82731610c1fb68b31670d6ce94a9e"))
    (library
      (name (snow genport))
      (path "snow/genport.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Generic ports." i/o snow)
      (license lgpl/v2.1)
      (depends (snow bytevector) (snow binio) (snow gauche-genport-utils)))
    (library
      (name (snow gauche-genport-utils))
      (path "snow/gauche-genport-utils.sld")
      (version "1.0")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "Generic ports." i/o snow)
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/hello.tgz")
    (size 3095)
    (checksum (md5 "45d0942d19553cd85cc0df6c3eace4e0"))
    (library
      (name (snow hello))
      (path "snow/hello.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Display \"let it snow\" and pi." example snow)
      (license lgpl/v2.1)
      (depends (snow pi))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/input-parse.tgz")
    (size 12311)
    (checksum (md5 "da94855dbd20890f97e87b0c4a78831f"))
    (library
      (name (snow input-parse))
      (path "snow/input-parse.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description
        "inspired and compatible with Oleg Kiselyov's input parsing library")
      (license public-domain)
      (depends (snow snowlib) (snow srfi-13-strings))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/pi.tgz")
    (size 4631)
    (checksum (md5 "7a3dff017131a37620db4713500f4541"))
    (library
      (name (snow pi))
      (path "snow/pi.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Computes the digits of pi." example snow)
      (license lgpl/v2.1)
      (depends (snow bignum))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/processio.tgz")
    (size 8727)
    (checksum (md5 "d210ba4eaaa9cbcf042b99963dd4c79f"))
    (library
      (name (snow processio))
      (path "snow/processio.sld")
      (version "1.0.0")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Seth Alves <alves@hungry.com")
      (authors
        "Nils M Holm <nmh at t3x.org>"
        "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "I/O to operating system subprocesses." i/o os)
      (license bsdl)
      (depends (snow snowlib) (snow filesys) (snow extio))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/random.tgz")
    (size 5143)
    (checksum (md5 "f44bb72f39d003490dc7b14edd3529af"))
    (library
      (name (snow random))
      (path "snow/random.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "High-quality random number generation." snow)
      (license lgpl/v2.1)
      (depends (snow bytevector) (snow binio) (snow bignum))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/snowlib.tgz")
    (size 14359)
    (checksum (md5 "6f1c9fecbc4841395df4dd9b0a34a1d1"))
    (library
      (name (snow snowlib))
      (path "snow/snowlib.sld")
      (version "1.2.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "Scheme Now! runtime library." snow)
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-13-strings.tgz")
    (size 16407)
    (checksum (md5 "1ce9fcccdef0f6710222ddaf64ae6869"))
    (library
      (name ())
      (path "snow/srfi-13-strings.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors)
      (description "srfi-13-strings")
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-19-time.tgz")
    (size 58903)
    (checksum (md5 "eaea8a9163622e1ab1947da929c1c34d"))
    (library
      (name (snow srfi-19-time))
      (path "snow/srfi-19-time.sld")
      (version "1.0")
      (homepage "http://srfi.schemers.org/srfi-19/srfi-19.html")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Will Fitzgerald" "Neodesic Corporation")
      (description "srfi-19-time")
      (license BSD-style)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-29-format.tgz")
    (size 10775)
    (checksum (md5 "004fd8f5b1f8b5b17886cbbc77df48ba"))
    (library
      (name (snow srfi-29-format))
      (path "snow/srfi-29-format.sld")
      (version "1.0")
      (homepage "http://srfi.schemers.org/srfi-29/srfi-29.html")
      (maintainers)
      (authors)
      (description "srfi-29-format")
      (license mit)
      (depends (snow snowlib))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-60-integers-as-bits.tgz")
    (size 9751)
    (checksum (md5 "56d7bd6613d6c4f88455f739c571b493"))
    (library
      (name (snow srfi-60-integers-as-bits))
      (path "snow/srfi-60-integers-as-bits.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "bytevector compatibility layer")
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/srfi-95-sort.tgz")
    (size 12823)
    (checksum (md5 "48058dec6d02a36de01264739eb90bb2"))
    (library
      (name (snow srfi-95-sort))
      (path "snow/srfi-95-sort.sld")
      (version "1.0")
      (homepage
        "http://srfi.schemers.org/srfi-95/srfi-95.html"
        "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Aubrey Jaffer" "Richard A. O'Keefe" "D.H.D. Warren")
      (description "Sorting and Merging")
      (license public-domain)
      (depends (snow gauche-sort-utils) (snow bytevector)))
    (library
      (name (snow gauche-sort-utils))
      (path "snow/gauche-sort-utils.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "Sorting and Merging")
      (license public-domain)
      (depends)))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/tar.tgz")
    (size 25111)
    (checksum (md5 "80aff466f198307938b21e22d49fd0b1"))
    (library
      (name (snow tar))
      (path "snow/tar.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors "Marc Feeley <feeley at iro.umontreal.ca>")
      (description "TAR file format packing and unpacking." conv snow)
      (license lgpl/v2.1)
      (depends
        (snow snowlib)
        (snow bytevector)
        (snow srfi-60-integers-as-bits)
        (snow bignum)
        (snow genport)
        (snow filesys))))
  (package
    (name ())
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/zlib.tgz")
    (size 45591)
    (checksum (md5 "c5d9f9edb240f60496f9e92666cabafa"))
    (library
      (name (snow zlib))
      (path "snow/zlib.sld")
      (version "1.0.1")
      (homepage "http://snow.iro.umontreal.ca")
      (maintainers "Scheme Now! <snow at iro.umontreal.ca>")
      (authors
        "Marc Feeley <feeley at iro.umontreal.ca>"
        "Manuel Serrano <Manuel.Serrano at sophia.inria.fr>")
      (description
        "Compression and decompression of deflate and gzip formats."
        conv
        i/o
        snow)
      (license lgpl/v2.1)
      (depends
        (snow snowlib)
        (snow bytevector)
        (snow digest)
        (snow srfi-60-integers-as-bits)
        (snow genport)))))
