(repository
  (sibling
    (name "Snow Repository")
    (url "http://snow-repository.s3-website-us-east-1.amazonaws.com/")
    (trust 1.0))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/aws.tgz")
    (size 19991)
    (checksum (md5 "470ac71b7e39e29223e1e284cbfa880f"))
    (library
      (name (seth aws s3))
      (path "seth/aws/s3.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Thomas Hintz <t@thintz.com>")
      (description "aws")
      (license BSD-style)
      (depends
        (snow snowlib)
        (snow bytevector)
        (snow srfi-13-strings)
        (snow extio)
        (seth uri)
        (seth port-extras)
        (seth xml ssax)
        (seth xml sxpath)
        (seth http)
        (seth aws common)))
    (library
      (name (seth aws common))
      (path "seth/aws/common.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Thomas Hintz <t@thintz.com>")
      (description "aws")
      (license BSD-style)
      (depends
        (snow bytevector)
        (snow srfi-13-strings)
        (snow srfi-95-sort)
        (snow srfi-29-format)
        (snow srfi-19-time)
        (snow extio)
        (seth xml ssax)
        (seth xml sxpath)
        (seth http)
        (seth crypt hmac-sha-1)
        (seth port-extras)
        (seth uri)
        (seth base64))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/base64.tgz")
    (size 13847)
    (checksum (md5 "50462eaf5ecd81b1357b047c5435d616"))
    (library
      (name (seth base64))
      (path "seth/base64.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "base64")
      (license lgpl/v2.1)
      (depends (snow bytevector))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/binary-pack.tgz")
    (size 5143)
    (checksum (md5 "6f50ce2b582b189d59526a89d960472f"))
    (library
      (name (seth binary-pack))
      (path "seth/binary-pack.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "binary-pack")
      (license lgpl/v2.1)
      (depends (snow bytevector))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/cout.tgz")
    (size 4119)
    (checksum (md5 "6ae63bdb4ef500636a5e0ab5e5ad2ceb"))
    (library
      (name (seth cout))
      (path "seth/cout.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "cout")
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/crypt.tgz")
    (size 52247)
    (checksum (md5 "5f6909474f2acf23b1dd07a4099fa9e7"))
    (library
      (name (seth crypt md5))
      (path "seth/crypt/md5.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Alex Shinn")
      (description "md5")
      (license BSD-style)
      (depends (snow bytevector) (snow srfi-60-integers-as-bits)))
    (library
      (name (seth crypt sha-1))
      (path "seth/crypt/sha-1.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "sha-1")
      (license BSD-style)
      (depends (snow bytevector) (snow srfi-60-integers-as-bits)))
    (library
      (name (seth crypt sha-2))
      (path "seth/crypt/sha-2.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Alex Shinn")
      (description "sha-2")
      (license BSD-style)
      (depends (snow bytevector) (snow srfi-60-integers-as-bits)))
    (library
      (name (seth crypt hmac-sha-1))
      (path "seth/crypt/hmac-sha-1.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "hmac-sha-1")
      (license BSD-style)
      (depends
        (snow bytevector)
        (snow srfi-60-integers-as-bits)
        (snow srfi-13-strings)
        (seth port-extras)
        (seth crypt sha-1))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/gensym.tgz")
    (size 3095)
    (checksum (md5 "d177f76ad3c70ee66e1a909a6b58061b"))
    (library
      (name (seth gensym))
      (path "seth/gensym.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "gensym")
      (license BSD-style)
      (depends)))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/http.tgz")
    (size 18967)
    (checksum (md5 "ace65fa93e520f3511e8d0619a6a51b5"))
    (library
      (name (seth http))
      (path "seth/http.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "http")
      (license lgpl/v2.1)
      (depends
        (snow snowlib)
        (snow gauche-extio-utils)
        (snow binio)
        (snow bytevector)
        (snow srfi-29-format)
        (snow srfi-13-strings)
        (snow extio)
        (seth mime)
        (seth string-read-write)
        (seth uri)
        (seth port-extras)
        (seth network-socket))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/memcache-client.tgz")
    (size 16919)
    (checksum (md5 "a8b74490bbeb8f30593cf8f076c5aa09"))
    (library
      (name (seth memcache-client))
      (path "seth/memcache-client.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "memcache-client")
      (license lgpl/v2.1)
      (depends
        (snow bytevector)
        (snow srfi-13-strings)
        (snow binio)
        (seth network-socket)
        (seth string-read-write)
        (seth port-extras)
        (seth base64))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/message-digest.tgz")
    (size 54807)
    (checksum (md5 "b183b1dc14601c3ca7a238b750952be8"))
    (library
      (name (seth message-digest parameters))
      (path "seth/message-digest/parameters.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Kon Lovett")
      (description "message-digest")
      (license BSD)
      (depends (seth variable-item)))
    (library
      (name (seth message-digest primitive))
      (path "seth/message-digest/primitive.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Kon Lovett")
      (description "message-digest")
      (license BSD)
      (depends (seth gensym)))
    (library
      (name (seth message-digest type))
      (path "seth/message-digest/type.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Kon Lovett")
      (description "message-digest")
      (license BSD)
      (depends
        (snow snowlib)
        (snow bytevector)
        (seth message-digest primitive)))
    (library
      (name (seth message-digest support))
      (path "seth/message-digest/support.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Kon Lovett")
      (description "message-digest")
      (license BSD)
      (depends (seth message-digest primitive) (seth message-digest type)))
    (library
      (name (seth message-digest bv))
      (path "seth/message-digest/bv.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Kon Lovett")
      (description "message-digest")
      (license BSD)
      (depends
        (seth message-digest primitive)
        (seth message-digest type)
        (seth message-digest support)))
    (library
      (name (seth message-digest port))
      (path "seth/message-digest/port.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Kon Lovett")
      (description "message-digest")
      (license BSD)
      (depends
        (seth string-read-write)
        (seth srfi-69-hash-tables)
        (seth message-digest primitive)
        (seth message-digest type)
        (seth message-digest bv)))
    (library
      (name (seth message-digest update-item))
      (path "seth/message-digest/update-item.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Kon Lovett")
      (description "message-digest")
      (license BSD)
      (depends
        (snow snowlib)
        (snow bytevector)
        (seth message-digest parameters)
        (seth message-digest primitive)
        (seth message-digest type)
        (seth message-digest support)))
    (library
      (name (seth message-digest md5))
      (path "seth/message-digest/md5.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Kon Lovett")
      (description "message-digest")
      (license BSD)
      (depends
        (snow bytevector)
        (snow srfi-60-integers-as-bits)
        (seth message-digest primitive)))
    (library
      (name (seth message-digest item))
      (path "seth/message-digest/item.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Kon Lovett")
      (description "message-digest")
      (license BSD)
      (depends (seth message-digest type) (seth message-digest update-item))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/mime.tgz")
    (size 18967)
    (checksum (md5 "03acc24be99ad2ee52d1c7a201e3bd41"))
    (library
      (name (seth mime))
      (path "seth/mime.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Alex Shinn")
      (description "RFC2045 MIME library")
      (license BSD-style "http://synthcode.com/license.txt")
      (depends
        (snow srfi-13-strings)
        (snow extio)
        (seth quoted-printable)
        (seth base64)
        (snow binio))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/network-socket.tgz")
    (size 27159)
    (checksum (md5 "48e43beefad43adf103a3888fcc28cae"))
    (library
      (name (seth network-socket))
      (path "seth/network-socket.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "network-socket")
      (license bsd)
      (depends
        (seth port-extras)
        (snow bytevector)
        (seth gauche-socket-utils)))
    (library
      (name (seth gauche-socket-utils))
      (path "seth/gauche-socket-utils.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "network-socket")
      (license bsd)
      (depends)))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/port-extras.tgz")
    (size 7703)
    (checksum (md5 "d0c36532ea1ddbc778a561f0db4b7c14"))
    (library
      (name (seth port-extras))
      (path "seth/port-extras.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "port-extras")
      (license lgpl/v2.1)
      (depends (snow bytevector) (snow binio) (seth string-read-write))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/quoted-printable.tgz")
    (size 9751)
    (checksum (md5 "a41d863aa26e80ce4b417d1cad2af374"))
    (library
      (name (seth quoted-printable))
      (path "seth/quoted-printable.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Alex Shinn")
      (description
        "RFC 2045 quoted printable encoding and decoding utilities.  This API is backwards compatible with the Gauche library rfc.quoted-printable.")
      (license BSD-style "http://synthcode.com/license.txt")
      (depends (snow srfi-60-integers-as-bits) (snow srfi-13-strings))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/snow2-utils.tgz")
    (size 79388)
    (checksum (md5 "830ecb6b189d01ad19a49d1eee20b5ed"))
    (library
      (name (seth snow2 client))
      (path "seth/snow2/client.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "snow2-utils")
      (license mit)
      (depends
        (snow snowlib)
        (snow extio)
        (snow srfi-13-strings)
        (seth srfi-69-hash-tables)
        (snow filesys)
        (snow binio)
        (snow genport)
        (snow zlib)
        (snow tar)
        (seth http)
        (seth temporary-file)
        (seth srfi-37-argument-processor)
        (seth string-read-write)
        (seth uri)
        (seth crypt md5)
        (seth snow2 types)
        (seth snow2 utils)
        (seth snow2 manage)))
    (library
      (name (seth snow2 manage))
      (path "seth/snow2/manage.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "snow2 types")
      (license mit)
      (depends
        (snow extio)
        (snow bytevector)
        (snow srfi-13-strings)
        (snow srfi-29-format)
        (snow filesys)
        (seth crypt md5)
        (snow zlib)
        (snow tar)
        (seth aws common)
        (seth aws s3)
        (seth uri)
        (seth snow2 types)
        (seth snow2 utils)
        (seth snow2 r7rs-library)
        (snow snowlib)))
    (library
      (name (seth snow2 types))
      (path "seth/snow2/types.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "snow2-utils")
      (license mit)
      (depends (seth uri)))
    (library
      (name (seth snow2 utils))
      (path "seth/snow2/utils.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "snow2-utils")
      (license mit)
      (depends
        (snow snowlib)
        (snow extio)
        (snow srfi-13-strings)
        (seth srfi-69-hash-tables)
        (snow filesys)
        (snow binio)
        (snow genport)
        (snow zlib)
        (snow tar)
        (seth http)
        (seth temporary-file)
        (seth string-read-write)
        (seth srfi-37-argument-processor)
        (seth uri)
        (seth snow2 types)))
    (library
      (name (seth snow2 r7rs-library))
      (path "seth/snow2/r7rs-library.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "snow2-utils")
      (license mit)
      (depends)))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/srfi-27-random.tgz")
    (size 3095)
    (checksum (md5 "0b8fb0ccf71e526f93e9f726b495fd20"))
    (library
      (name (seth srfi-27-random))
      (path "seth/srfi-27-random.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "srfi-27-random")
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/srfi-37-argument-processor.tgz")
    (size 13335)
    (checksum (md5 "4d17849f19836e77b6b47e415ec0910e"))
    (library
      (name (seth srfi-37-argument-processor))
      (path "seth/srfi-37-argument-processor.sld")
      (version "1.0")
      (homepage "http://srfi.schemers.org/srfi-37/srfi-37.html")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Anthony Carrico")
      (description "srfi-27-random")
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/srfi-69-hash-tables.tgz")
    (size 18455)
    (checksum (md5 "4615257e876ef94dcd5259641dbda5f6"))
    (library
      (name (seth srfi-69-hash-tables))
      (path "seth/srfi-69-hash-tables.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "srfi-69-hash-tables")
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/string-read-write.tgz")
    (size 4119)
    (checksum (md5 "f61a3bcd2e463f8ebfe0fcd87a40f6df"))
    (library
      (name (seth string-read-write))
      (path "seth/string-read-write.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "string-read-write")
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/tar.tgz")
    (size 3607)
    (checksum (md5 "8a7ab983416282d3f0515fb4a5ad1c9e"))
    (library
      (name (seth tar))
      (path "seth/tar.sld")
      (version "1.3")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "shell out to tar")
      (license lgpl/v2.1)
      (depends)))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/temporary-file.tgz")
    (size 5143)
    (checksum (md5 "aab3411f42af65c8e06b0ebd4bdbe4a0"))
    (library
      (name (seth temporary-file))
      (path "seth/temporary-file.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "temporary-file")
      (license lgpl/v2.1)
      (depends (seth srfi-27-random))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/uri.tgz")
    (size 45591)
    (checksum (md5 "fabc36309baaa1f5b9e29f43f45d2dd6"))
    (library
      (name (seth uri))
      (path "seth/uri.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Ivan Raikov" "Peter Bex")
      (description "uri")
      (license bsd)
      (depends
        (snow snowlib)
        (snow srfi-13-strings)
        (seth string-read-write))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/uuid.tgz")
    (size 5655)
    (checksum (md5 "d9078c095a759be180767b9d107e6ac7"))
    (library
      (name (seth uuid))
      (path "seth/uuid.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "parse and generate uuids")
      (license lgpl/v2.1)
      (depends
        (snow bytevector)
        (snow srfi-60-integers-as-bits)
        (seth binary-pack)
        (snow srfi-13-strings)
        (seth srfi-27-random))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/variable-item.tgz")
    (size 5655)
    (checksum (md5 "eda5e539ab3d6fa6d0a7985e48213ef8"))
    (library
      (name (seth variable-item))
      (path "seth/variable-item.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Kon Lovett")
      (description "variable-item")
      (license BSD-style)
      (depends)))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/xml.tgz")
    (size 332336)
    (checksum (md5 "2e42c2917f357c81cbd4751b8f6df989"))
    (library
      (name (seth xml ssax))
      (path "seth/xml/ssax.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Oleg Kiselyov")
      (description "XML parser")
      (license public-domain)
      (depends
        (snow snowlib)
        (snow assert)
        (snow input-parse)
        (snow srfi-13-strings)))
    (library
      (name (seth xml sxpath))
      (path "seth/xml/sxpath.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors)
      (description "XML parser")
      (license public-domain)
      (depends
        (snow snowlib)
        (snow extio)
        (snow assert)
        (snow srfi-13-strings))))
  (package
    (name ())
    (url "http://snow2.s3-website-us-east-1.amazonaws.com/zlib.tgz")
    (size 6679)
    (checksum (md5 "260beaa6a299d001afa68116b4bbb8a2"))
    (library
      (name (seth zlib))
      (path "seth/zlib.sld")
      (version "1.0")
      (homepage "https://github.com/sethalves")
      (maintainers "Seth Alves <seth@hungry.com>")
      (authors "Seth Alves <seth@hungry.com>")
      (description "zlib")
      (license BSD-style)
      (depends
        (snow genport)
        (snow bytevector)
        (seth port-extras)
        (snow zlib)))))
